name: 'chiaro-oscuro'
description: 'AI-powered logo generation for light and dark themes using GitHub Models'
author: 'Jason McPheron'

branding:
  icon: 'sun'
  color: 'yellow'

inputs:
  project-name:
    description: 'Name of your project or repository'
    required: true
  description:
    description: 'Brief description of what your project does'
    required: true
  style:
    description: 'Logo design style (modern, minimal, playful, corporate, tech)'
    required: false
    default: 'modern'
  github-token:
    description: 'GitHub token for API access'
    required: true
    default: ${{ github.token }}
  output-dir:
    description: 'Directory for generated logos'
    required: false
    default: 'assets'
  model:
    description: 'AI model (github/gpt-4o-mini, github/llama-3.1-70b-instruct, github/deepseek-r1)'
    required: false
    default: 'github/gpt-4o-mini'
  branch-name:
    description: 'Branch name for PR'
    required: false
    default: 'chiaro-oscuro/generate-logo'
  commit-message:
    description: 'Commit message'
    required: false
    default: 'Add AI-generated logo for light and dark themes'
  pr-title:
    description: 'Pull request title'
    required: false
    default: 'Add theme-aware logo generated by AI'

outputs:
  light-logo-path:
    description: 'Path to the generated light theme logo'
  dark-logo-path:
    description: 'Path to the generated dark theme logo'
  pr-url:
    description: 'URL of the created pull request'

runs:
  using: 'composite'
  steps:
    - name: Validate inputs
      shell: bash
      run: |
        if [ -z "${{ inputs.project-name }}" ]; then
          echo "❌ Project name is required"
          exit 1
        fi
        if [ -z "${{ inputs.description }}" ]; then
          echo "❌ Project description is required"
          exit 1
        fi
        echo "✅ Project: ${{ inputs.project-name }}"
        echo "📝 Description: ${{ inputs.description }}"
        echo "🎨 Style: ${{ inputs.style }}"
    
    - name: Set up Python and UV
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install UV
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"
    
    - name: Install dependencies and LLM plugins
      shell: bash
      run: |
        cd ${{ github.action_path }}
        echo "📦 Installing dependencies with UV..."
        uv sync --dev
        
        echo "🔌 Installing LLM GitHub Models plugin..."
        uv run llm install llm-github-models
        
        echo "🔍 Verifying LLM setup..."
        uv run llm --version
        uv run llm models list | grep -E "(github|gpt|llama)" || echo "No GitHub models found yet - will be available after first use"
    
    - name: Generate logo variants using LLM CLI
      shell: bash
      env:
        GITHUB_MODELS_KEY: ${{ inputs.github-token }}
      run: |
        cd ${{ github.action_path }}
        echo "🎨 Generating logo variants using LLM CLI..."
        
        # Read the logo generation prompt template
        PROMPT_TEMPLATE=$(cat prompts/generate-logo.txt)
        
        # Replace placeholders with actual values
        PROMPT="${PROMPT_TEMPLATE//\{\{PROJECT_NAME\}\}/${{ inputs.project-name }}}"
        PROMPT="${PROMPT//\{\{DESCRIPTION\}\}/${{ inputs.description }}}"
        PROMPT="${PROMPT//\{\{STYLE\}\}/${{ inputs.style }}}"
        
        # Generate logos using LLM CLI
        echo "🤖 Running AI inference with model: ${{ inputs.model }}"
        echo "$PROMPT" | uv run llm prompt \
          -m "${{ inputs.model }}" \
          --system "You are a professional logo designer. Create clean, modern SVG logos that work well in both light and dark themes." \
          > /tmp/logo_response.txt
        
        # Check if generation was successful
        if [ $? -eq 0 ] && [ -s /tmp/logo_response.txt ]; then
          echo "✅ Logo generation completed"
          echo "📊 Response size: $(wc -c < /tmp/logo_response.txt) characters"
          echo "📝 Response preview:"
          head -3 /tmp/logo_response.txt
        else
          echo "❌ Logo generation failed"
          exit 1
        fi
    
    - name: Process AI responses and save logos
      shell: bash
      env:
        OUTPUT_DIR: ${{ inputs.output-dir }}
        LOGO_RESPONSE_FILE: /tmp/logo_response.txt
      run: |
        cd ${{ github.action_path }}
        echo "🔄 Processing AI responses..."
        # Run in the action directory but save to workspace
        OUTPUT_DIR="${GITHUB_WORKSPACE}/${{ inputs.output-dir }}" \
        uv run python src/process_logos_llm.py
    
    - name: Create pull request with optimized logos
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        BRANCH_NAME: ${{ inputs.branch-name }}
        COMMIT_MESSAGE: ${{ inputs.commit-message }}
        PR_TITLE: ${{ inputs.pr-title }}
      run: |
        # Change to workspace directory
        cd "${GITHUB_WORKSPACE}"
        
        # Debug: Show where we are and what files exist
        echo "Current directory: $(pwd)"
        echo "Files in assets directory:"
        ls -la ${{ inputs.output-dir }}/ || echo "No assets directory found"
        echo "Git status before configuration:"
        git status --porcelain
        
        # Configure git
        git config --global user.name "chiaro-oscuro[bot]"
        git config --global user.email "action@github.com"
        
        # Force add the files to ensure they're tracked
        git add -f ${{ inputs.output-dir }}/logo-*.svg README.md || {
          echo "Failed to add files. Checking what's available:"
          find . -name "*.svg" -type f
          exit 1
        }
        
        # Check if there are changes to commit
        if git diff --staged --quiet; then
          echo "No changes to commit after staging"
          echo "Git status:"
          git status
          echo "Files that should exist:"
          ls -la ${{ inputs.output-dir }}/logo-*.svg README.md
          exit 0
        fi
        
        # Delete existing branch if it exists
        git push origin --delete "$BRANCH_NAME" 2>/dev/null || true
        
        # Create and switch to new branch
        git checkout -b "$BRANCH_NAME"
        
        # Commit changes (files already staged above)
        git commit -m "$COMMIT_MESSAGE"
        
        # Push branch
        git push origin "$BRANCH_NAME"
        
        # Create pull request using GitHub CLI
        echo "Creating pull request..."
        echo "Branch: $BRANCH_NAME"
        echo "Repository: ${{ github.repository }}"
        
        # Set PR URL output
        PR_URL=$(gh pr create \
          --title "$PR_TITLE" \
          --body "🤖 AI-generated logo for ${{ inputs.project-name }}" \
          --head "$BRANCH_NAME" \
          --base main 2>&1) || {
          echo "⚠️ Could not create PR automatically. Error:"
          echo "$PR_URL"
          echo ""
          echo "Please create the PR manually from branch: $BRANCH_NAME"
          echo "The branch has been pushed and contains your new logos."
          exit 0
        }
        
        echo "✅ Pull request created: $PR_URL"
        
        # Set output
        if [ -n "$GITHUB_OUTPUT" ]; then
          echo "pr-url=$PR_URL" >> "$GITHUB_OUTPUT"
        fi